/*
 * This file is generated by jOOQ.
 */
package io.github.yip.db;


import io.github.yip.db.tables.UserIslamicInfoSettings;
import io.github.yip.db.tables.records.UserIslamicInfoSettingsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserIslamicInfoSettingsRecord> USER_ISLAMIC_INFO_SETTINGS_PKEY = Internal.createUniqueKey(UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS, DSL.name("user_islamic_info_settings_pkey"), new TableField[] { UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS.USER_ID }, true);
}
