/*
 * This file is generated by jOOQ.
 */
package io.github.yip.db;


import io.github.yip.db.tables.UserIslamicInfoSettings;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user_islamic_info_settings</code>.
     */
    public static final UserIslamicInfoSettings USER_ISLAMIC_INFO_SETTINGS = UserIslamicInfoSettings.USER_ISLAMIC_INFO_SETTINGS;
}
