/*
 * This file is generated by jOOQ.
 */
package io.github.yip.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserIslamicInfoSettings implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long quranReciterId;
    private final Long islamicSchoolId;

    public UserIslamicInfoSettings(UserIslamicInfoSettings value) {
        this.userId = value.userId;
        this.quranReciterId = value.quranReciterId;
        this.islamicSchoolId = value.islamicSchoolId;
    }

    public UserIslamicInfoSettings(
        Long userId,
        Long quranReciterId,
        Long islamicSchoolId
    ) {
        this.userId = userId;
        this.quranReciterId = quranReciterId;
        this.islamicSchoolId = islamicSchoolId;
    }

    /**
     * Getter for <code>public.user_islamic_info_settings.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for
     * <code>public.user_islamic_info_settings.quran_reciter_id</code>.
     */
    public Long getQuranReciterId() {
        return this.quranReciterId;
    }

    /**
     * Getter for
     * <code>public.user_islamic_info_settings.islamic_school_id</code>.
     */
    public Long getIslamicSchoolId() {
        return this.islamicSchoolId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserIslamicInfoSettings other = (UserIslamicInfoSettings) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.quranReciterId == null) {
            if (other.quranReciterId != null)
                return false;
        }
        else if (!this.quranReciterId.equals(other.quranReciterId))
            return false;
        if (this.islamicSchoolId == null) {
            if (other.islamicSchoolId != null)
                return false;
        }
        else if (!this.islamicSchoolId.equals(other.islamicSchoolId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.quranReciterId == null) ? 0 : this.quranReciterId.hashCode());
        result = prime * result + ((this.islamicSchoolId == null) ? 0 : this.islamicSchoolId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserIslamicInfoSettings (");

        sb.append(userId);
        sb.append(", ").append(quranReciterId);
        sb.append(", ").append(islamicSchoolId);

        sb.append(")");
        return sb.toString();
    }
}
